.set      z64_SpawnActor,         0x800BAE14
.set      z64_SpawnActorIndirect, 0x800BB2D0
.set      z64_UpdateButtonIcon,   0x80112B40
.set      z64_PlaySound,          0x801A5CFC

.set      z64_state_ovl_tab,      0x801BD910
.set      z64_object_table,       0x801C2740
.set      z64_scene_table,        0x801C3CA0
.set      z64_file,               0x801EF670
.set      z64_afx,                0x80200C70
.set      z64_afx_cmd_write_pos,  (z64_afx + 0x00007978)
.set      z64_afx_cmd_buf,        (z64_afx + 0x000079F4)
.set      z64_ctxt,               0x803E6B20
.set      z64_scene_index,        (z64_ctxt + 0x000000A4)
.set      z64_scene_ptr,          (z64_ctxt + 0x000000B0)
.set      z64_obj_ctxt,           (z64_ctxt + 0x00017D88)
.set      z64_room_ctxt,          (z64_ctxt + 0x000186E0)
.set      z64_room_list,          (z64_ctxt + 0x0001884C)
