export const enum ModLoaderErrorCodes {
  NORMAL_EXIT,
  UNKNOWN,
  NO_ROM,
  BPS_FAILED,
  BAD_VERSION,
  MISSING_EMULATOR_PLUGIN,
  EMULATOR_CORE_FAILURE,
  BAD_LOBBY_PASSWORD,
  ML_CORE_REFUSED_ROM,
  MISSING_CORE
}
