/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2020-07-16 07:59:09 
*/

import { Listener } from "./sfml_audio";


export interface ISoundSystem {
    loadSound(file: string): any;
    initSound(buf: Buffer): any;
    loadMusic(file: string): any;
    initMusic(buf: Buffer): any;
    listener: Listener;
}

export class FakeSoundImpl implements ISoundSystem{
    listener!: Listener;
    loadSound(file: string) {
    }
    initSound(buf: Buffer) {
    }
    loadMusic(file: string) {
    }
    initMusic(buf: Buffer) {
    }
}