.set      z64_SpawnActor,         0x80025110
.set      z64_SpawnActorIndirect, 0x800255C4
.set      z64_UpdateButtonIcon,   0x8006FB50
.set      z64_PlaySound,          0x800C806C

.set      z64_state_ovl_tab,      0x800F1340
.set      z64_object_table,       0x800F8FF8
.set      z64_scene_table,        0x800FB4E0
.set      z64_file,               0x8011A5D0
.set      z64_afx,                0x80125630
.set      z64_afx_cmd_write_pos,  (z64_afx + 0x00005BD8)
.set      z64_afx_cmd_buf,        (z64_afx + 0x00005C50)
.set      z64_ctxt,               0x801C84A0
.set      z64_scene_index,        (z64_ctxt + 0x000000A4)
.set      z64_scene_ptr,          (z64_ctxt + 0x000000B0)
.set      z64_obj_ctxt,           (z64_ctxt + 0x000117A4)
.set      z64_room_ctxt,          (z64_ctxt + 0x00011CBC)
.set      z64_room_list,          (z64_ctxt + 0x00011DF0)
