/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2020-04-01 04:34:19 
*/

export interface IAnalytics {
    send(key: string, data: any): void;
    retrieve(key: string): void;
}
