/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2020-11-02 00:19:36 
*/
export interface IAnalyticsManager {
    stats: any;
    storeStat(key: string, object: any): void;
    getStat(key: string): any;
}
